<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Dashboard</title>
  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .nav>li>a:hover,
    .nav>li>a:focus {
      background-color: #17a2b8;
      color: #FFC0CB;
      font-size: x-large;
    }
  </style>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <!-- Custom styles for this template -->
  <link href="http://localhost:8080/css/dashboard.css" rel="stylesheet">
</head>

<body>
  <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"> -->
    <div class="navbar-nav d-flex flex-row">
      <div class="nav-item p-2">
        <a class="nav-link px-3 h5 text-info " href="../../index" id="logout">Go to Website</a>
      </div>
      <div class="nav-item p-2">

        <a class="nav-link px-3 h5 text-info" href="../../login/logout" id="logout">Sign out</a>
      </div>
    </div>
  </header>

  <div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light collapse">
        <div class="position-sticky pt-3">
          <ul class="nav flex-column">
            <li class="nav-item">
              <p class="nav-link h4 active user-dashboard">Hello <?php echo $_SESSION['user']['name'] ?></p>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="http://localhost:8080/dashboard/blogDashboard">
                <span data-feather="shopping-cart"></span>
                Manage Blogs
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="http://localhost:8080/dashboard/userDashboard">
                <span data-feather="users"></span>
                Manage Users
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="http://localhost:8080/dashboard/createBlog">
                <span data-feather="users"></span>
                Publish a blog
              </a>
            </li>
          </ul>
        </div>
      </nav>
      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2 text-info">Dashboard</h1>
        </div>

