<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BlogXpriya</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        #intro {
            /* Margin to fix overlapping fixed navbar */
            margin-top: 58px;
        }

        .card-img {
            height: 320px;
        }

        @media (max-width: 991px) {
            #intro {
                /* Margin to fix overlapping fixed navbar */
                margin-top: 45px;
            }
        }
    </style>
</head>

<body>
    <div class="container-fluid">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <!-- Navbar brand -->
            <a href="http://localhost:8080/index"><img class="navbar-brand" height="100" alt="logo" loading="lazy" style="margin-top: -3px;" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhgWcEqRO-AjQozC_P0mj2VU4v5vnC61qUBQ&usqp=CAU"></a>

            <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarExample01" aria-controls="navbarExample01" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarExample01">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" aria-current="page" href="index">Home</a>
                    </li>
                    <li class="nav-item active">
                        <?php echo (isset($this->session->id) and $this->session->role !== 'reader') ?
                            '<a class="nav-link" aria-current="page" href="dashboard">Dashboard</a>' :
                            '<a class="nav-link" aria-current="page" href="#">Become a writer</a>'; ?></li>
                    <!-- <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="dashboard">Dashboard</a>
                        </li> -->
                    <li class="nav-item">
                        <?php echo isset($this->session->role) ? '<a class="nav-link" href="http://localhost:8080/login/logout">Logout</a>'
                            : '<a class="nav-link" href="login">Login</a>'; ?>
                    </li>
                </ul>

                <ul class="navbar-nav d-flex flex-row">
                    <!-- Icons -->
                    <li class="nav-item me-3 me-lg-0">
                        <a class="nav-link" href="https://www.youtube.com/channel/UC5CF7mLQZhvx8O5GODZAhdA" rel="nofollow" target="_blank">
                            <i class="fab fa-youtube"></i>
                        </a>
                    </li>
                    <li class="nav-item me-3 me-lg-0">
                        <a class="nav-link" href="https://www.facebook.com/mdbootstrap" rel="nofollow" target="_blank">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                    </li>
                    <li class="nav-item me-3 me-lg-0">
                        <a class="nav-link" href="https://twitter.com/MDBootstrap" rel="nofollow" target="_blank">
                            <i class="fab fa-twitter"></i>
                        </a>
                    </li>
                    <li class="nav-item me-3 me-lg-0">
                        <a class="nav-link" href="https://github.com/mdbootstrap/mdb-ui-kit" rel="nofollow" target="_blank">
                            <i class="fab fa-github"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Navbar -->
    <!--Main Navigation-->
<!--Main layout-->
<div class="my-5">
    <div class="container">
        <!-- Category Grid-->
        <section class="page-section bg-light" id="portfolio">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Categories</h2>
                    <h3 class="section-subheading text-muted">Browse blogs by category.</h3>
                </div>
                <div class="row" id="category">
                    <?php foreach ($categories as $category) {
                        echo '<div class="col-lg-4 col-sm-6 mb-4">
                    <div class="portfolio-item">
                        <div class="portfolio-content d-flex flex-column align-items-center">
                            <div class="portfolio-image mb-2">
                                <a class="portfolio-link" href="http://localhost:8080/blog/category/' . $category->category_id . '">
                                    <img class="img-fluid" src="http://localhost:8080/public/img/category/' . $category->img . '" alt="category-image" />
                                </a>
                            </div>
                            <h3 class="section-heading text-uppercase">' . $category->name . '</h3>
                        </div>
                    </div>
                    </div>';
                    }
                    ?>
                </div>
            </div>
        </section>
        <!--Section:Main Content-->
        <section class="text-center">
            <h4 class="mb-5"><strong>Latest posts</strong></h4>

            <div class="row">
                <?php
                foreach ($posts as $post) {
                    echo '<div class="col-lg-4 col-md-12 mb-4">
                            <div class="card">
                                <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                                    <img src="img/thumbnail/' . $post->post_img . '" class="img-fluid card-img" />
                                    <a href="#!">
                                        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                                    </a>
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title">' . $post->post_title . '</h5>
                                    <p class="card-text">
                                    ' . substr_replace($post->thumbnail, "...", 150) . '
                                    </p>
                                    <a href="http://localhost:8080/blog/index/' . $post->post_id . '" class="btn btn-primary">Read</a>
                                </div>
                            </div>
                        </div>';
                }
                ?>
        </section>
        <!--Section: Content-->

        
    </div>
            </div>
<!--Main layout-->
            </div>
<!--Footer-->
<footer class="bg-light text-lg-start">
    <hr class="m-0" />
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2020 Copyright:
        <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
</footer>
<!--Footer-->
</body>

</html>