<?php
include_once("utility/sidenav.phtml");
?>
<h2 id="section-title">User Dashboard</h2>
<div class="table-responsive">
  <div id="table-div"></div>
  <table class="table table-striped table-sm" id="dashboard-table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">User Id</th>
        <th scope="col">Name</th>
        <th scope="col">E-mail</th>
        <?php if ($_SESSION['user']['role'] == 'admin') {

          echo '<th scope="col">Role</th>
      <th scope="col">Change Status</th><th>Delete User</th>
    </tr>
  </thead>';
          foreach ($users as $k => $data) {
            echo $data->role !== 'admin' ? "<tr><td scope='row'>" . $k . "</td>
            <td>" . $data->user_id . "</td>
            <td>" . $data->name . "</td>
            <td>" . $data->email . "</td>
            <td>" . $data->role . "</td>
            <td>
            <a href='editUser/" . $data->user_id . "' class='btn btnsm btn-success " . ($data->role == 'reader' ? 'invisible' : 'visible') . "'>Mark Reader<a>
            <a href='editUser/" . $data->user_id . "' class='btn btnsm btn-warning " . ($data->role == 'reader' ? 'visible' : 'invisible') . "'>Mark Writer</a>
            </td>
            <td><a href='deleteUser/" . $data->user_id . "' class='btn btn-danger'>Delete User</a></td>
            </tr>" : '';
          }
        } else {
          echo '</tr></thead>';
          echo "<tr><td scope='row'>#</td>
            <td>" . $user->user_id . "</td>
            <td>" . $user->name . "</td>
            <td>" . $user->email . "</td>
            </tr>";
        }
        ?>
  </table>
  <?php
include_once("utility/footer.phtml");